### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure about this error:
```
E   RuntimeError: error during blosc decompression: -1
numcodecs/blosc.pyx:392: RuntimeError
```

**Comment by rabernat** [comment]
Thanks so much for this @davidbrochart!

The blosc errors are intermittent. I see them a lot. We should probably report that error in numcodecs.

**Comment by rabernat** [comment]
xref https://github.com/pangeo-data/pangeo/issues/196 for blosc issue

It failed again on the master build: https://github.com/pangeo-forge/pangeo-forge/runs/1754269723?check_suite_focus=true

**Comment by rabernat** [comment]
p.s. If you are keen to contribute to the docs, we would love to have some help with #38! 😉

**Pull request merged**
