### PR TITLE
Create cmip6-recipe.ipynb

### PR DESCRIPTION
**Pull request by naomi-henderson**
I am having trouble previewing this notebook - hopefully it is alright.  If not, I could provide a link to the file instead.

### CODE REVIEW

**Comment by rabernat** [comment]
Fantastic Naomi! If you want to have this actually show up in the docs, you need to include your new notebook in the index this file: https://github.com/pangeo-forge/pangeo-forge/blob/master/docs/tutorials/index.md

ReadTheDocs has built a preview of this PR - https://pangeo-forge--103.org.readthedocs.build/en/103/ - but as you can see, the new nb is not there, for the reason above.

**Comment by rabernat** [comment]
Sorry for the unclear instructions... You should add the file to _this_ PR, not create a new PR (#104).

**Comment by naomi-henderson** [comment]
okay, I will try again 8-)

**Comment by naomi-henderson** [comment]
okay, I guess I have quick fiddling with it for now. It is ready to be merged after review. thanks!

**Comment by naomi-henderson** [comment]
@rabernat , could you merge this pull request when you get a chance? I do not have, nor do I need, write access to this repository. THANKS!

**Pull request merged**
