### PR TITLE
Pin xarray to unreleased master and rechunker to 0.4.2 for use with pip.

### LINKED ISSUE #111: Pin xarray to a compatible version.
Since https://github.com/pydata/xarray/pull/5065/ has been merged it would be helpful to pin xarray to the Github `master` branch in `requirements.txt` in the interim until the `safe_chunks` functionality is in release.  Currently installing `pangeo_forge` in the image for our Dask workers requires special install ordering to avoid `pangeo-forge` potentially using a cached xarray version.

### PR DESCRIPTION
**Pull request by sharkinsspatial**
Closes #111

### CODE REVIEW

**Comment by sharkinsspatial** [comment]
@rabernat After merging, can you create a new release as well since `0.2.0`'s `requirements.txt` contains this non-existent `xarray` version https://github.com/pangeo-forge/pangeo-forge/commit/ad82fb63898e3b0d1aa761230a454d27678bc2fe.

**Review by rabernat — APPROVED** [review]
Thanks Sean!

**Comment by rabernat** [comment]
I think we have a hung test.

**Comment by rabernat** [comment]
> After merging, can you create a new release as well since `0.2.0`'s `requirements.txt` contains this non-existent `xarray` version [ad82fb6](https://github.com/pangeo-forge/pangeo-forge/commit/ad82fb63898e3b0d1aa761230a454d27678bc2fe).

I'm not sure that's what you want. If we create a new release now from master, it will also include the refactor of #101, which will probably break your test recipes. I guess we should have done this _before_ the 0.2.0 release. 🤦 

In any case, xarray 0.17.1 will be released any day now.

**Comment by sharkinsspatial** [comment]
@rabernat I've updated both [pangeo-forge-prefect](https://github.com/pangeo-forge/pangeo-forge-prefect/pull/1/files) and my PR against [staged-recipes](https://github.com/pangeo-forge/staged-recipes/pull/28/commits/05762b252cd3c81da1f0fe0a336a50eb19ac8264) to use the changes from #101 and run the recipe on our bakery as a test.  Is there any other breaking changes in `master` that I have not taken into account?

**Pull request merged**
